language: minimal
sudo: required
services:
  - docker
deploy:
  - provider: script
    script: bash deploy.sh
    on:
      condition: $TRAVIS_COMMIT_MESSAGE =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+[0-9A-Za-z-]+)?$
branches:
  only:
    - master